 import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f0f0f",
    padding: 20,
    paddingTop: 60,
  },
  title: { color: "#fff", fontSize: 28, fontWeight: "bold", marginBottom: 20 },
  subtitle: {
    color: "#aaa",
    fontSize: 12,
    textTransform: "uppercase",
    marginVertical: 12,
  },
  scanBtn: {
    backgroundColor: "#1a1a1a",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  scanBtnText: { color: "#4ade80", fontWeight: "bold" },
  scanningWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
  },
  scanningText: { color: "#4ade80", fontSize: 13 },
  device: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#1a1a1a",
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  deviceSelected: {
    borderWidth: 1,
    borderColor: "#4ade80",
    backgroundColor: "#1a2e1a",
  },
  deviceIcon: { fontSize: 24 },
  deviceName: { color: "#fff", fontWeight: "bold" },
  deviceIP: { color: "#666", fontSize: 12 },
  empty: { color: "#555", textAlign: "center", marginTop: 20 },
  progressWrap: {
    height: 32,
    backgroundColor: "#1a1a1a",
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  progressBar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "#4ade80",
  },
  progressText: { color: "#fff", fontSize: 12 },
  sendBtn: {
    backgroundColor: "#4ade80",
    padding: 16,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 8,
  },
  sendBtnDisabled: { backgroundColor: "#4ade80", opacity: 0.5 },
  sendBtnText: { color: "#000", fontWeight: "bold", fontSize: 16 },
});